<h1> Transformación de los datos</h1>

<p>El propósito es realizar una transformación de los datos para mejorar el análisis</p>

<h2> Importar los datos </h2>

In [2]:
import pandas as pd
import matplotlib.pylab as plt
import numpy as np

In [3]:
df = pd.read_csv("https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DA0101EN/auto.csv",
                names = ["symboling","normalized-losses","make","fuel-type","aspiration", "num-of-doors","body-style",
         "drive-wheels","engine-location","wheel-base", "length","width","height","curb-weight","engine-type",
         "num-of-cylinders", "engine-size","fuel-system","bore","stroke","compression-ratio","horsepower",
         "peak-rpm","city-mpg","highway-mpg","price"])

In [4]:
df.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450

<h2> Como trabajar con los datos perdidos </h2
   <div>
    Pasos:
    <ol>
        <li>Identificar los datos perdidos</li>
        <li>Actuar sobre estos datos</li>
        <li>Corregir el formato de todos los datos</li>
    </ol>   
    </div>

<h3>Convertir "?" en NaN </h3>

In [5]:
# replace "?" to NaN
df.replace("?", np.nan, inplace = True)
df.dtypes

symboling              int64
normalized-losses     object
make                  object
fuel-type             object
aspiration            object
num-of-doors          object
body-style            object
drive-wheels          object
engine-location       object
wheel-base           float64
length               float64
width                float64
height               float64
curb-weight            int64
engine-type           object
num-of-cylinders      object
engine-size            int64
fuel-system           object
bore                  object
stroke                object
compression-ratio    float64
horsepower            object
peak-rpm              object
city-mpg               int64
highway-mpg            int64
price                 object
dtype: object

<h3> Identificando valores pérdidos</h3>
<p> el método <code> .isnull()</code> permite encontrar los valores pérdidos (False) para poder ser reemplazados 
    más facilmente </p>

In [6]:
missing_data = df.isnull() 
# también existe .notnull()
missing_data.tail()# checking missing values 
# True -> missing value NaN
# False -> not a missing value

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
200,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
201,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
202,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
203,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
204,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [7]:
columns = missing_data.columns.values.tolist() # lista con los encabezados de las columnas
print(columns)

['symboling', 'normalized-losses', 'make', 'fuel-type', 'aspiration', 'num-of-doors', 'body-style', 'drive-wheels', 'engine-location', 'wheel-base', 'length', 'width', 'height', 'curb-weight', 'engine-type', 'num-of-cylinders', 'engine-size', 'fuel-system', 'bore', 'stroke', 'compression-ratio', 'horsepower', 'peak-rpm', 'city-mpg', 'highway-mpg', 'price']

In [8]:
for column in columns:
    print(column)
    print(missing_data[column].value_counts()) # counts True and False values
    print('----------')

symboling
False    205
Name: symboling, dtype: int64
----------
normalized-losses
False    164
True      41
Name: normalized-losses, dtype: int64
----------
make
False    205
Name: make, dtype: int64
----------
fuel-type
False    205
Name: fuel-type, dtype: int64
----------
aspiration
False    205
Name: aspiration, dtype: int64
----------
num-of-doors
False    203
True       2
Name: num-of-doors, dtype: int64
----------
body-style
False    205
Name: body-style, dtype: int64
----------
drive-wheels
False    205
Name: drive-wheels, dtype: int64
----------
engine-location
False    205
Name: engine-location, dtype: int64
----------
wheel-base
False    205
Name: wheel-base, dtype: int64
----------
length
False    205
Name: length, dtype: int64
----------
width
False    205
Name: width, dtype: int64
----------
height
False    205
Name: height, dtype: int64
----------
curb-weight
False    205
Name: curb-weight, dtype: int64
----------
engine-type
False    205
Name: engine-type, dtype: int64
----------
num-of-cylinders
False    205
Name: num-of-cylinders, dtype: int64
----------
engine-size
False    205
Name: engine-size, dtype: int64
----------
fuel-system
False    205
Name: fuel-system, dtype: int64
----------
bore
False    201
True       4
Name: bore, dtype: int64
----------
stroke
False    201
True       4
Name: stroke, dtype: int64
----------
compression-ratio
False    205
Name: compression-ratio, dtype: int64
----------
horsepower
False    203
True       2
Name: horsepower, dtype: int64
----------
peak-rpm
False    203
True       2
Name: peak-rpm, dtype: int64
----------
city-mpg
False    205
Name: city-mpg, dtype: int64
----------
highway-mpg
False    205
Name: highway-mpg, dtype: int64
----------
price
False    201
True       4
Name: price, dtype: int64
----------

<h3> Resolver el problema de valores perdidos </h3>
 <ol>
    <li>Eliminar el dato:<br>
        a. Eliminar todo el registro. (fila)
        b. Eliminar la columna.
    </li>
    <li>
        Reemplazar el dato:<br>
        a. Reemplazar por el promedio. <br>
        b. Reemplazar por el dato de mayor frecuecia<br>
        c. Reemplazarlo en base a otras funciones
    </li>
 </ol>

<h3>Reemplazar por el promedio </h3>

In [22]:

avg_norm_loss = df['normalized-losses'].astype("float").mean(axis = 0)
print(f"avg_norm_loss: {avg_norm_loss}")
df['normalized-losses'].replace(np.nan, avg_norm_loss, inplace = True)

avg_norm_loss: 122.0

In [25]:
avg_bore = df['bore'].astype("float").mean(axis = 0)
print(avg_bore)
df['bore'].replace(np.nan, avg_bore, inplace = True)

3.3297512437810957

<h3>Reemplazar por dato de mayor frecuencia </h3>

In [11]:
df['num-of-doors'].value_counts().idxmax() # most frequent value

'four'

In [34]:
df['num-of-doors'].replace(np.nan,df['num-of-doors'].value_counts().idxmax(), inplace = True)

In [36]:
df['num-of-doors'].value_counts()

four    116
two      89
Name: num-of-doors, dtype: int64

In [37]:
# change data type
df.dtypes

symboling              int64
normalized-losses     object
make                  object
fuel-type             object
aspiration            object
num-of-doors          object
body-style            object
drive-wheels          object
engine-location       object
wheel-base           float64
length               float64
width                float64
height               float64
curb-weight            int64
engine-type           object
num-of-cylinders      object
engine-size            int64
fuel-system           object
bore                  object
stroke                object
compression-ratio    float64
horsepower            object
peak-rpm              object
city-mpg               int64
highway-mpg            int64
price                 object
dtype: object

In [38]:
df[["peak-rpm"]] = df[["peak-rpm"]].astype("float")

In [39]:
df.dtypes

symboling              int64
normalized-losses     object
make                  object
fuel-type             object
aspiration            object
num-of-doors          object
body-style            object
drive-wheels          object
engine-location       object
wheel-base           float64
length               float64
width                float64
height               float64
curb-weight            int64
engine-type           object
num-of-cylinders      object
engine-size            int64
fuel-system           object
bore                  object
stroke                object
compression-ratio    float64
horsepower            object
peak-rpm             float64
city-mpg               int64
highway-mpg            int64
price                 object
dtype: object

In [40]:
# Convert mpg to L/100km
df['city-L/100km'] = 235/df["city-mpg"]

# check your transformed data 
df.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,city-L/100km
0,3,122,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,mpfi,3.47,2.68,9.0,111,5000.0,21,27,13495,11.190476
1,3,122,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,mpfi,3.47,2.68,9.0,111,5000.0,21,27,16500,11.190476
2,1,122,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,mpfi,2.68,3.47,9.0,154,5000.0,19,26,16500,12.368421
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,mpfi,3.19,3.40,10.0,102,5500.0,24,30,13950,9.791667
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,mpfi,3.19,3.40,8.0,115,5500.0,18,22,17450,13.055556

In [42]:
df.columns.values.tolist()

['symboling',
 'normalized-losses',
 'make',
 'fuel-type',
 'aspiration',
 'num-of-doors',
 'body-style',
 'drive-wheels',
 'engine-location',
 'wheel-base',
 'length',
 'width',
 'height',
 'curb-weight',
 'engine-type',
 'num-of-cylinders',
 'engine-size',
 'fuel-system',
 'bore',
 'stroke',
 'compression-ratio',
 'horsepower',
 'peak-rpm',
 'city-mpg',
 'highway-mpg',
 'price',
 'city-L/100km']

In [50]:
# normalize 'stroke' column
df['stroke'] = df['stroke'].astype('float')
df['stroke'] = df['stroke']/df['stroke'].max()

In [51]:
df.head(10)

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,city-L/100km
0,3,122,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,mpfi,3.47,0.642686,9.0,111,5000.0,21,27,13495,11.190476
1,3,122,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,mpfi,3.47,0.642686,9.0,111,5000.0,21,27,16500,11.190476
2,1,122,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,mpfi,2.68,0.832134,9.0,154,5000.0,19,26,16500,12.368421
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,mpfi,3.19,0.815348,10.0,102,5500.0,24,30,13950,9.791667
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,mpfi,3.19,0.815348,8.0,115,5500.0,18,22,17450,13.055556
5,2,122,audi,gas,std,two,sedan,fwd,front,99.8,...,mpfi,3.19,0.815348,8.5,110,5500.0,19,25,15250,12.368421
6,1,158,audi,gas,std,four,sedan,fwd,front,105.8,...,mpfi,3.19,0.815348,8.5,110,5500.0,19,25,17710,12.368421
7,1,122,audi,gas,std,four,wagon,fwd,front,105.8,...,mpfi,3.19,0.815348,8.5,110,5500.0,19,25,18920,12.368421
8,1,158,audi,gas,turbo,four,sedan,fwd,front,105.8,...,mpfi,3.13,0.815348,8.3,140,5500.0,17,20,23875,13.823529
9,0,122,audi,gas,turbo,two,hatchback,4wd,front,99.5,...,mpfi,3.13,0.815348,7.0,160,5500.0,16,22,NaN,14.687500

KeyError: "['borr'] not in index"